### ISSUE TITLE
not showing more than one worker per host

### ISSUE THREAD

**Issue by f8-ptrk** [s0nik42/lotus-farcaster#10]
we are running multiple workers on a single host. 

the dashboard is only showing one worker.

![2020-12-13_21-45](https://user-images.githubusercontent.com/60559388/102013651-83bf4c00-3d8c-11eb-8ad1-151b30c41840.png)

the idefix 1/2 hosts have 2 workers each. the total worker count is 9+1 miner --> 10

the workers use one GPU each, so there is information missing about one GPU used on these hosts (i wouldn't care otherwise how many workers are shown/host in that section)

**Comment by PatrickDeuse** [comment]
it is actually showing the 2 workers in the workers section

![Uploading 2020-12-14_09-06.png…]()

**Comment by PatrickDeuse** [comment]
i have to step back from the comment i made. i shows only one worker in the "worker resources" section too. I thought it's showing too but on a seconds look its one CPU and GPU / host

**Comment by s0nik42** [comment]
That won't change, lotus is designed to work like this.
