### ISSUE TITLE
ERROR http://10.10.0.1:14200/rpc/v0 returned no result

### ISSUE THREAD

**Issue by f8-ptrk** [s0nik42/lotus-farcaster#12]
ERROR http://10.10.0.1:14200/rpc/v0 returned no result
DEBUG: method StateMarketStorageDeal / params [1213665, []] 
DEBUG: {'jsonrpc': '2.0', 'id': 3, 'error': {'code': 1, 'message': 'deal 1213665 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed'}} 
ERROR http://10.10.0.1:14200/rpc/v0 returned no result
DEBUG: method StateMarketStorageDeal / params [1213664, []] 
DEBUG: {'jsonrpc': '2.0', 'id': 3, 'error': {'code': 1, 'message': 'deal 1213664 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed'}} 

get spammed with mails!

**Comment by s0nik42** [comment]
What about now the new version ?
