### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by PatrickDeuse** [s0nik42/lotus-farcaster#13]
when installing and using the user "filecoin" the cron job is installed with "filecoin" as user - even if that user has no write access to var/lib/prometheus/node-exporter

debian 10

**Comment by s0nik42** [comment]
Could you confirm if you install the prometheus-node-exporter before launching the install script or if you let the install script install it for you ?

**Comment by PatrickDeuse** [comment]
i think i can confirm that. i first installed the dependencies. i will give it another shot since the calibration net seems to be up to date now.

but it shouldn't matter. a package installed by apt should'n be able to know who installed it.

**Comment by s0nik42** [comment]
that's correct. but the install script set the rights on the /var/lib/prometheus/node-exporter . So I think if it's failing it's because the rights are removed by node-exporter (like when it's running the first time or something)

**Comment by s0nik42** [comment]
You can try running the install script a second time, to see if it solves the problem

**Comment by s0nik42** [comment]
Not enough information to reproduce the bug. I modified the code. We will see if it corrects it.
