### ISSUE TITLE
feature req: show base gas fee

### ISSUE THREAD

**Issue by f8-ptrk** [s0nik42/lotus-farcaster#14]
since 1.2.2 the base gas fee is shown with lotus-miner info

it would be nice to have it in the dashboard

**Comment by s0nik42** [comment]
For the next version : 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/30711794/103598139-2ab58480-4f02-11eb-98c4-cf21dc4f8196.png">
<img width="644" alt="image" src="https://user-images.githubusercontent.com/30711794/103598170-3dc85480-4f02-11eb-91fa-12ce82a4fb2c.png">

**Comment by s0nik42** [comment]
Nope, I just don't have history yet as it's a new feature

**Comment by s0nik42** [comment]
Implemented in the next release
