### ISSUE TITLE
typo + wrong info in "Others" section 

### ISSUE THREAD

**Issue by PatrickDeuse** [s0nik42/lotus-farcaster#17]
![2020-12-13_21-53](https://user-images.githubusercontent.com/60559388/102013870-c46b9500-3d8d-11eb-96c4-1e0dfd7d25b4.png)

you see the typo. and the info is wrong - the miner is below 10TB due to post failure see: #11

**Comment by PatrickDeuse** [comment]
forget about the wrong info part, just the typo left, see #11

**Comment by s0nik42** [comment]
Corrected. I will include it in the next release.
