### ISSUE TITLE
Message Method to "Messagename" mappings

### ISSUE THREAD

**Issue by f8-ptrk** [s0nik42/lotus-farcaster#19]
Seems that not all methods have corresponding strings implemented

![2020-12-18_09-59](https://user-images.githubusercontent.com/60559388/102565211-ef504300-4117-11eb-85ed-daf0d631639a.png)

**Comment by s0nik42** [comment]
that's correct, if you've got the full list, I'm intrested in.

**Comment by PatrickDeuse** [comment]
https://github.com/filecoin-project/specs-actors/blob/v2.3.2/actors/builtin/methods.go#L78

**Comment by PatrickDeuse** [comment]
might not be the up to date one - too many updates too fast these days, but that's where they are listed

**Comment by s0nik42** [comment]
I asked the question to PL. If you look at it carefully, you see that different method type have the same number. Method 4 as an exemple is used for PublishStorageDeals but also ChangePeerId ... Do you know how to identify which one I should match ?

**Comment by PatrickDeuse** [comment]
the address they are coming from.

**Comment by s0nik42** [comment]
Included in V2
