### ISSUE TITLE
Feature requests: daily power changes and Burn Fees

### ISSUE THREAD

**Issue by William8Work** [s0nik42/lotus-farcaster#21]
Would be great to see the following graph:

1. Daily changes on the sectors status / power changes: new sectors added since last winpost, or show this numbers under the existing "Miner Power" graph, or "Other-Miner Power" graph.

2. Burn fees are quite a concern for miners. Would be great to show a graph for the burn fees, and weekly or monthly total accumulated fees if possible.

**Comment by s0nik42** [comment]
@William8Work thank you for your feedback. 

1/ I think the information you are looking for are provided by the graph named : "MINER POWER" and "STORED SECTOR STATE". Could you please confirm if it helps ?

2/ by Burn fee you would expect something like : the total fee you have personnally burned on a specific miner ?

**Comment by William8Work** [comment]
for 1). I added a simple graph to illustrate that, see the attachment. 
![Screenshot from 2021-01-04 17-19-49](https://user-images.githubusercontent.com/3475205/103595802-3cbb0700-4eb1-11eb-8dcd-4c5d668379e1.png)

2). yes. I saw a lot of discussion in the slack channel asking that - it will drive tons of interests. Just don't know how easy to get the data. In terms of format, it would be great to show a Total Burn Fee, as well as Month-to-Date Burn Fee, if possible. I am paying about 5 FILs each day for burn fees to seal.

**Comment by s0nik42** [comment]
1/ Sorry, the attachment looks like a screenshot from farcaster, I don't see what's new here :) 

2/ yes, I'm thinking of it. what you are looking for is an onchain information; to retrieve this we will have to parse the chain, farcaster is  designed to pull  realtime information from lotus. Pulling from the chain is a much slower and another type of request, this is more what Filfox is doing. 

How will you see it ? a website or receiving a daily reports will be fine ?

**Comment by William8Work** [comment]
1/ The "Active Sectors", and "Faulty" are two graphs I added to farcaster by myself. I'm using the data you already have.

2/. Probably it doesn't have to be real time, I guess having the numbers in web site would be more convenience. 

thanks!

**Comment by s0nik42** [comment]
Added to the new version
