### ISSUE TITLE
Feature Request: support multi processes in single worker

### ISSUE THREAD

**Issue by William8Work** [s0nik42/lotus-farcaster#22]
As a miner, I would like to see my multiple lotus processes running within a single worker machine appearing in the "Worker" section of farcaster dashboard so that I can monitor the status on each of them.

**Background:**
I was able to mange to run two C2 processes in a single worker machine, each of them using different port, and different GPU. However, farcaster only shows one.

**Challenges:**
when using lotus-miner sealing workers, these two C2 processes showing up as separate Id and entry but both of them are using the same host name (because they are running in the same machine). It would be good for forcaster to list them separately under the Worker section.

**Comment by PatrickDeuse** [comment]
see #10

**Comment by William8Work** [comment]
close as this is a duplicate to #10. Thanks @PatrickDeuse!
