### ISSUE TITLE
Feature Request: WinningPost information, last block, time variance, luck, etc.

### ISSUE THREAD

**Issue by shawnp0wers** [s0nik42/lotus-farcaster#24]
This wasn't an issue for me until I crossed the mining threshold, lol -- but instead of scouring logs for "did I miss a block", it would be great to see some historic data about blocks mined along with details on the calculation time variance, misses, etc. I'm not sure if that info is available any way other than grepping logs though, so it might be impractical.

**Comment by s0nik42** [comment]
Won't be possible with farcaster  this information is not available in lotus ! but I'm cooking something for you
