### ISSUE TITLE
lotus user?

### ISSUE THREAD

**Issue by Jasonwu123** [s0nik42/lotus-farcaster#29]
Hi, what is the LOTUS_USER_USERNAME???  How does it mean??

**Comment by s0nik42** [comment]
The name of the user running the lotus process

**Comment by Jasonwu123** [comment]
> The name of the user running the lotus process

But my lotus process is running in other machine.  And my lotus miner worker are all the same user name, how dose resolve it?? Thanks

**Comment by s0nik42** [comment]
Let me understand

The miner and the node are on 2 different servers?

You don't have to deploy it on the workers

**Comment by s0nik42** [comment]
@Jasonwu123 have you make it work ?

**Comment by Jasonwu123** [comment]
> Let me understand The miner and the node are on 2 different servers? You don't have to deploy it on the workers
> […](#)
> Sent from my iPhone
> On 5 Aug 2021, at 04:03, Jasonwu ***@***.***> wrote: ﻿ The name of the user running the lotus process But my lotus process is running in other machine. And my lotus miner worker are all the same user name, how dose resolve it?? Thanks — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

yeah, I got it. I mean, lotus miner and lotus node are deployed on different machines in the LAN. And then they hostname is the same, for example call lotus-xl.

**Comment by Jasonwu123** [comment]
So, when I execute the `sudo ./check.sh xl` command, it has the following error:

`Check if xl exist : [ OK ]
Check if xl is a lotus user : [ OK ]
Check if lotus-exporter-farcaster.py run properly : [Errno 2] No such file or directory: '/home/xl/.lotusminer/api'
[ KO ] error encountered :
         # HELP lotus_local_time time on the node machine when last execution start in epoch
         # TYPE lotus_local_time gauge
         lotus_local_time {  } 1628586485
         # HELP lotus_scrape_execution_succeed return 1 if lotus-farcaster execution was successfully
         # TYPE lotus_scrape_execution_succeed gauge
         lotus_scrape_execution_succeed {  } -2
TODO : run manually : sudo -u xl /usr/local/bin/lotus-exporter-farcaster.py`

Then, I run the ` sudo -u xl /usr/local/bin/lotus-exporter-farcaster.py` command according to the TODO prompt. But it continues to prompt errors:
`# HELP lotus_local_time time on the node machine when last execution start in epoch
# TYPE lotus_local_time gauge
lotus_local_time {  } 1628586762
# HELP lotus_scrape_execution_succeed return 1 if lotus-farcaster execution was successfully
# TYPE lotus_scrape_execution_succeed gauge
lotus_scrape_execution_succeed {  } -2
[Errno 2] No such file or directory: '/home/xl/.lotusminer/api'`

 What should I do next???

**Comment by s0nik42** [comment]
Where is your .lotusminer location ?

**Comment by s0nik42** [comment]
Following our slack discussion all good. I close the ticket
