### ISSUE TITLE
CRON Error Message

### ISSUE THREAD

**Issue by shawnp0wers** [s0nik42/lotus-farcaster#3]
After installing based on instructions (On Ubuntu 20.04.1), the cronjob gives this error every minute:

```
Traceback (most recent call last):
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 616, in <module>
    main()
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 212, in main
    miner_control0 = daemon_stats["result"]["ControlAddresses"][0]
TypeError: 'NoneType' object is not subscriptable
? 
```

**Comment by s0nik42** [comment]
Ok, nice catch, it's because you don't have control0 adress on your miner, let me fix this tonight

**Comment by shawnp0wers** [comment]
Got another cron error. The dashboard stopped updating, and my mail box is full of these:

```
Traceback (most recent call last):
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 616, in <module>
    main()
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 268, in main
    if base_info["result"]["EligibleForMining"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by shawnp0wers** [comment]
Oh, sorry -- I did a git pull and it seems to have changed.

Now I get this, which is unsettling:
```
ERROR MinerGetBaseInfo return no result
KNOWN_REASON your miner reports wrong info to the chain and thats pretty bad (not just for the dashboard)
SOLUTION restart your miner and node
```

The miner seems to be working fine... but i'll admit, the error is worrisome!

**Comment by s0nik42** [comment]
yeah, you are not the only one reporting this. to get read of it you have to restart daemon and miner. This is not related to the script. It seems like your miner is not reporting elligibility and power correctly to the Chain

**Comment by s0nik42** [comment]
can you try restarting your miner and let me know if the error disappeared from the log ?

**Comment by shawnp0wers** [comment]
I restarted the lotus-miner and the lotus(daemon), the issue persists. Unless you meant restart the entire machine?

**Comment by s0nik42** [comment]
whats you  miner id ?

**Comment by shawnp0wers** [comment]
f071624

```
    # Mining eligibility
    print("# HELP lotus_power_mining_eligibility return miner mining eligibility")
    print("# TYPE lotus_power_mining_eligibility gauge")
    base_info = daemon_get_json("MinerGetBaseInfo", [miner_id, chainhead["result"]["Height"], tipsetkey])

    if base_info["result"] is None:
        print(f'ERROR MinerGetBaseInfo return no result', file=sys.stderr)
        print(f'KNOWN_REASON your miner reports wrong info to the chain and thats pretty bad (not just for the dashboard)', file=sys.stderr)
        print(f'SOLUTION restart your miner and node', file=sys.stderr)
        print('lotus_scrape_execution_succeed { } 0')
        sys.exit(0)

    if base_info["result"]["EligibleForMining"]:
        eligibility = 1
    else:
        eligibility = 0
    print(f'lotus_power_mining_eligibility {{ miner_id="{miner_id}" }} { eligibility }')
    checkpoint("Power")
```

**Comment by s0nik42** [comment]
@shawnp0wers , the call works (see below) are you sure you still have the issue ?
 
{'jsonrpc': '2.0', 'result': {'MinerPower': '3023656976384', 'NetworkPower': '1398906384122871808', 'Sectors': [{'SealProof': 3, 'SectorNumber': 42, 'SealedCID': {'/': 'bagboea4b5abcbutxfwvzfyj7w4in7r2tyzqwce6k2keyqjkikrjsx56xh24yu6sc'}}], 'WorkerKey': 'f3vewwfwaf2paiygmlf5pfyr6y26ot6h2q3kfnqjtj6mpqhbo4pxdjsral6xnxa4lcob6slnv254vocymreq6a', 'SectorSize': 34359738368, 'PrevBeaconEntry': {'Round': 389446, 'Data': 'pDjCRe8fJy63kpHbCqGy+FDHYBojWur0LyyErvY80mzrB8XUsL6vn2nRPzkySq+sFSglm9p1E2dgyK0x8lAofIbQK76yui0+1yfa8z2Q5DCIr+UvsZzDIKJmLjeNShNc'}, 'BeaconEntries': None, 'EligibleForMining': False}, 'id': 3}

**Comment by shawnp0wers** [comment]
I had disabled it -- but I just reenabled, and it's working. What was the issue? I did recompile to the most recent version of lotus this morning...

**Comment by s0nik42** [comment]
I did nothing, it was like your node was not reporting information properly, did you mine during that time ?
