### ISSUE TITLE
Ideas for lotus-farcaster v3

### ISSUE THREAD

**Issue by benjaminh83** [s0nik42/lotus-farcaster#30]
I'm a daily user of farcaster and basically run most of my storage provider operation from info generated on the platform. As filecoin is moving from phase 1 to phase 2, and deals get more and more important, its very obvious that lotus cli tools has no meaningful visualization tools to monitor and handle incoming deals. `lotus-miner storage-deals list` is becoming useless as I write...

I see a new version of farcaster including a seperate dashboard (so running two screens). One screen showing the sealing, storage and chain data (as we know farcaster today), and one screen delivering the deal related insights - here are some ideas for a second dash: 

- Move market node peers to here
- List of deals divided into the different stages: transferring, validating, staging, publishing 
- Statistics on clients - accepts and rejections per client/wallet(s)
- Move resource load on market node(s) to here
- monitoring of the AP from the market node (check efficiency / staging of deals into one sector)  
- live cost analysis on fees per deal when batching (help set realistic prices on smaller deals)   

There is probably plenty more. My hope is that it can be collected it a one-screen super dense view, like we know from the current dashboard.

**Comment by s0nik42** [comment]
Hi Ben, I want through all the points above. The current lotus API doesn't give tha bility to build such dashboards. The main reason is the speed. He takes More that 1min on my miner just ro retrieve the list of deals without further analisys.
Would be good to know from CryptoWizzard or Reiers how much it takes on their setup. 

 We worked with PL to propose a new version of the API that will drastically improve the performance and provide us the ability to build such dashboard. 

I proposed to keep your request open until then.
