### ISSUE TITLE
check.sh failed to start

### ISSUE THREAD

**Issue by 434314846** [s0nik42/lotus-farcaster#35]
Hellow ,Detect errors after installation 
install.sh
![图片](https://user-images.githubusercontent.com/42730891/135061214-c94cb10f-e633-454e-9c07-143ce95e0bda.png)

check.sh
![1](https://user-images.githubusercontent.com/42730891/135061608-f7a9254a-5b2c-4eb6-be65-883a4fcc4292.png)

**Comment by s0nik42** [comment]
Hi, 
Could you share the miner ID and the output of the command showing at the end of the last screenshot (TODO: run man....)

Thank you

**Comment by 434314846** [comment]
The 2k test network I use ,The execution result is the same as above 
![图片](https://user-images.githubusercontent.com/42730891/135188915-6ccbd0ca-7733-4548-aedd-870a1ff53663.png)

I will print line 1207 detail 
![图片](https://user-images.githubusercontent.com/42730891/135189357-6a93a977-16e5-4ae9-8d3d-3a3f11235a23.png)
![图片](https://user-images.githubusercontent.com/42730891/135189446-efcccf5f-b531-49e8-b862-8eaa422c9037.png)

**Comment by s0nik42** [comment]
Are all these tests performed on testnet or have you tried on mainnet OR calibnet ?

**Comment by 434314846** [comment]
All tests are based on testnet tests

**Comment by s0nik42** [comment]
Ok, that's probably the reason. This piece of code is where it calculated the Power on the network, could be that your machine has genesis blocks without creation date or something similar.

So for now, I recommend to test it on calib

We plan to deploy a testnest in the coming weeks, so I will be able to confirm my assumption at that time.

**Comment by 434314846** [comment]
Ok thanks
