### ISSUE TITLE
Can I monitor more then one Miner?

### ISSUE THREAD

**Issue by PatHoo** [s0nik42/lotus-farcaster#38]
I have two miner on the same node, how can I monitor then within one place?

**Comment by s0nik42** [comment]
Just to understand, You mean 2 lotus-miners are running on the same server ?

**Comment by PatHoo** [comment]
Yes, one 32G miner, one 64G miner. Just calibration network.

**Comment by s0nik42** [comment]
I will add it in the next version coming soon, you will add multiple miner on the same box (this might require a few manual steps).

**Comment by PatHoo** [comment]
OK
