### ISSUE TITLE
Exit on "not found error"

### ISSUE THREAD

**Issue by cryptowhizzard** [s0nik42/lotus-farcaster#4]
ERROR http://127.0.0.1:1234/rpc/v0 returned no result : 
DEBUG : {'jsonrpc': '2.0', 'id': 3, 'error': {'code': 1, 'message': 'deal 1246079 not found'}}

**Comment by s0nik42** [comment]
Hi @cryptowhizzard, 
Could you tell me in which state is the sector containing this deal ?

**Comment by s0nik42** [comment]
Could you confirm if the patch solve the problem ?

**Comment by cryptowhizzard** [comment]
Yes, this one is solved.

**Comment by s0nik42** [comment]
cool ! the deal should appear in grafana as unknown/0 value. Could you share a screenshot ?
Thanks, 
Julien
