### ISSUE TITLE
The content is messed up after translation

### ISSUE THREAD

**Issue by Subp66** [s0nik42/lotus-farcaster#45]
![微信截图_20220303155336](https://user-images.githubusercontent.com/39667572/156522259-3226b9a8-786e-4704-978a-8ddb3c9627d1.png)
`      "timeFrom": null,
      "timeShift": null,
      "title": "时空证明",
      "transformations": [
        {
          "id": "seriesToColumns",
          "options": {
            "byField": "index"
          }
        },
        {
          "id": "organize",
          "options": {
            "excludeByName": {
              "Time": true,
              "Time 1": true,
              "Time 2": true,
              "Time 3": true,
              "Time 4": true,
              "Time 5": true,
              "__name__": true,
              "__name__ 1": true,
              "__name__ 2": true,
              "__name__ 3": true,
              "__name__ 4": true,
              "instance": true,
              "instance 1": true,
              "instance 2": true,
              "instance 3": true,
              "instance 4": true,
              "instance 5": true,
              "job": true,
              "job 1": true,
              "job 2": true,
              "job 3": true,
              "job 4": true,
              "job 5": true,
              "miner_id": true,
              "miner_id 1": true,
              "miner_id 2": true,
              "miner_id 3": true,
              "miner_id 4": true,
              "miner_id 5": true
            },
            "indexByName": {
              "Time": 1,
              "Value #A": 6,
              "Value #B": 9,
              "Value #C": 10,
              "Value #D": 11,
              "Value #E": 7,
              "Value #F": 8,
              "__name__": 2,
              "index": 0,
              "instance": 3,
              "job": 4,
              "miner_id": 5
            },
            "renameByName": {
              "Value #A": "开始时间",
              "Value #B": "全部扇区",
              "Value #C": "恢复扇区",
              "Value #D": "失败扇区",
              "Value #E": "有效扇区",
              "Value #F": "Proven Partition",
              "index": "Id",
              "miner_id": ""
            }
          }
        }
      ]`

I am trying to change the title to Chinese, the time will become a numerical value, is it because my translation method is incorrect? Can you provide a complete translation solution?

**Comment by s0nik42** [comment]
hi @Subp66, 

Labels in panel are used as also used as ID (grafana limitation), which means when you change a label you also have to change it in all location referring to it like in the transform section  or override section (right pane)

If you agree to release your translation opensource, I can include it in the project. 

![image](https://user-images.githubusercontent.com/30711794/156932827-89f7bb9d-8f0d-45a1-b413-70c5a1d2f5bb.png)
![image](https://user-images.githubusercontent.com/30711794/156932884-a9b84a62-6d29-4898-b62e-816d679b7005.png)

**Comment by s0nik42** [comment]
no response. I close the ticket
