### ISSUE TITLE
Venus support?

### ISSUE THREAD

**Issue by Fatman13** [s0nik42/lotus-farcaster#46]
Hello team! I am wondering if farcaster currently supports Venus implementation of filecoin?

**Comment by s0nik42** [comment]
Hey @Fatman13 unfortunately, we only integrate lotus/boost

**Comment by Fatman13** [comment]
@s0nik42 Understood. Wondering if there is any plan to support Venus in the future? if so maybe we can push farcaster to Venus community too.

**Comment by s0nik42** [comment]
The way we build farcaster it's should not be to difficult to integrate a new implementation. 
Farcaster is opensource, I will be happy to support someone from the Venus community looking to develop it.  

Do you know how many Venus users ?

**Comment by Fatman13** [comment]
[Venus Community](https://filecoinproject.slack.com/archives/CEHHJNJS3) has around 300P of storage power. Venus community is looking for some metrics monitoring solution that they can use for their storage system. farcaster has been around from the very beginning. Thought people may not need to reinvent the wheel if they could just use farcaster. 

Will see if anyone from the community is interested in PRing some integration.
