### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ThomasBlock** [s0nik42/lotus-farcaster#47]
lotus-miner version 1.16.1
Ubuntu 20.04

i can not install lotus-farcaster. Install script runs through, but then this happens. I have split market node, no boost

lotus-exporter-farcaster.py   --debug
_# HELP lotus_scrape_execution_succeed return 1 if lotus-farcaster execution was successfully
_# TYPE lotus_scrape_execution_succeed gauge
lotus_scrape_execution_succeed {  } 0
ERROR: Traceback (most recent call last):
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 1615, in main
    run(args, output=sys.stdout)
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 1582, in run
    collect(daemon, miner, markets, metrics, addresses_config)
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 1435, in collect
    pending_publish_deals = markets.get_pending_publish_deals()["dealPublish"]
TypeError: 'NoneType' object is not subscriptable

**Comment by s0nik42** [comment]
Hi @ThomasBlock ,

The problem come from lotus-market you are correct; 
Lotus-markets is going to be deprecated, so I switched to boost and cannot really replicate the issue :/ 
I will have a look to see if I can point the issue.

Do you have any plan to switch to boost any time soonsoon ?

**Comment by ThomasBlock** [comment]
Hi! Thank you for the fast response. I am upgrading my monolithic process step by step, so i will probably also have a look at boost soon, yes.. So i can wait.

**Comment by s0nik42** [comment]
Before splitting did farcaster working on monolitic ?

**Comment by manojkumardevisetty** [comment]
[ KO ] error encountered : 
	 # HELP lotus_scrape_execution_succeed return 1 if lotus-farcaster execution was successfully
	 # TYPE lotus_scrape_execution_succeed gauge
	 lotus_scrape_execution_succeed {  } 0
 I don't have market node so i have changed it to miner api but the problem still seems not rectified

**Comment by ThomasBlock** [comment]
I fixed it now by upgrading to lotus 17.1 and boost 1.4. there was an error in install.sh ( ImportError: No module named toml ) , but seems to be working now

**Comment by s0nik42** [comment]
all good then
