### ISSUE TITLE
Can't get "lotus_info" output on curl localhost:9100

### ISSUE THREAD

**Issue by rjan90** [s0nik42/lotus-farcaster#5]
Finished the installation and got to the testing part:
```
FARCASTER INSTALLATION COMPLETED

********************************************************************************

TESTING : 
	curl -s -o - http://localhost:9100/metrics -s |grep "lotus_info"

```
I can get other metrics, but there is no lotus_info metric in there.

From the syslog I found:

```
Dec  3 12:29:01 CRON[2448262]: (root) CMD (if /usr/local/bin/lotus-exporter-farcaster.py > /var
/lib/prometheus/node-exporter/farcaster.prom.$$;  then mv /var/lib/prometheus/node-exporter/farcaster.prom.$$ /var/lib/promet
heus/node-exporter/farcaster.prom; else rm /var/lib/prometheus/node-exporter/farcaster.prom.$$; fi )
```

**Comment by cryptowhizzard** [comment]
Try running command python3 /usr/local/bin/lotus-exporter-farcaster.py and see what error you get. The Cron has an if / else script. If you have an error it won't write the data to /var/lib/prometheus/node-exporter/farcaster.prom

**Comment by rjan90** [comment]
Ah, I see! I have .lotusminer on a different path than what's specified in the script!

**Comment by rjan90** [comment]
Okay, fixed up the paths to .lotusminer & .lotus. Now I get:
`ERROR accessing http://127.0.0.1:34421/rpc/v0 : Unauthorized`

**Comment by s0nik42** [comment]
@rjan90, don't fix the script : 
Option 1/  set the variables at the top of the script. MINER_URL/MINER_TOKEN/ DAEMON_URL/DAEMON_TOKEN. 
OPtion 2/ More elegant I think,  create 2 symlink in your HOME. 
   - ln -s XXXXX/.lotus ~/   
   - ln -s XXXXX/.lotusminer ~/

**Comment by s0nik42** [comment]
let me know if it works

**Comment by rjan90** [comment]
@s0nik42 Okay, I tested editing the variables at the top of the script, and putting in my API Listen Adress in MINER_URL/MINER_TOKEN/ DAEMON_URL/DAEMON_TOKEN.

But I'm getting `ERROR accessing MINER_URL : Unauthorized`

**Comment by s0nik42** [comment]
yes, are you sure you took the right token file ?

**Comment by rjan90** [comment]
I accidentally copied additional text when adding the token file. You know, fridays can be hard..
