### ISSUE TITLE
No output when curl localhost

### ISSUE THREAD

**Issue by kaoxiang07** [s0nik42/lotus-farcaster#8]
I had finished the installation, when I test it with `curl -s -o - http://localhost:9100/metrics -s |grep "lotus_info"`, it output nothing.
When I run `python3 /usr/local/bin/lotus-exporter-farcaster.py`, the output became normal with lots of information of miner and lotus node, but it reports error at last:
`Traceback (most recent call last):
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 656, in <module>
    main()
  File "/usr/local/bin/lotus-exporter-farcaster.py", line 406, in main
    gpus = len(info["Resources"]["GPUs"])
TypeError: object of type 'NoneType' has no len()
`

**Comment by kaoxiang07** [comment]
BTW the error log in /var/log/syslog are following:
`Dec  9 16:54:19 u0146 CRON[61920]: (CRON) info (No MTA installed, discarding output)
Dec  9 16:55:01 u0146 CRON[62229]: (root) CMD (if /usr/local/bin/lotus-exporter-farcaster.py > /var/lib/prometheus/node-exporter/farcaster.prom.$$;  then mv /var/lib/prometheus/node-exporter/farcaster.prom.$$ /var/lib/prometheus/node-exporter/farcaster.prom; else rm /var/lib/prometheus/node-exporter/farcaster.prom.$$; fi )
`

**Comment by s0nik42** [comment]
That's strange it's like you've got one worker not reporting GPU information. Did you disconnect a worker since your last miner reboot ?

**Comment by kaoxiang07** [comment]
yes, I had. That worker is temporarily offline, could I use the dashboard with a worker offline? Or is there something other wrong?

**Comment by s0nik42** [comment]
normally yes, but there is a bug in lotus they report the worker being partially online that's why. I will have some control in the script to manage this case; in the meantime you can restart your miner or worker and all should be fine.
